steps:
  # Deploy to Google Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'rag-service'
      - '--image'
      - 'us-east1-docker.pkg.dev/just-skyline-474622-e1/rag/rag:$SHORT_SHA'
      - '--region'
      - 'us-east1'
      - '--allow-unauthenticated'
      - '--service-account'
      - 'cloud-run-backend@just-skyline-474622-e1.iam.gserviceaccount.com'
      - '--min-instances'
      - '1'
      - '--max-instances'
      - '10'
      - '--memory'
      - '8Gi'
      - '--cpu'
      - '2'
      - '--set-env-vars'
      - 'UVICORN_WORKERS=1,SECRET_PROJECT_ID=just-skyline-474622-e1,CE_MODEL=BAAI/bge-reranker-base'
      - '--update-secrets'
      - 'OPENAI_API_KEY=OPENAI_API_KEY:latest,PINECONE_API_KEY=PINECONE_API_KEY:latest,PINECONE_API_ENVIRONMENT=PINECONE_API_ENVIRONMENT:latest'

images:
  - 'gcr.io/just-skyline-474622-e1/rag:$SHORT_SHA'

# Define the secrets to be available as environment variables in the Cloud Run service
availableSecrets:
  secretManager:
    - versionName: projects/just-skyline-474622-e1/secrets/OPENAI_API_KEY/versions/latest
      env: 'OPENAI_API_KEY'
    - versionName: projects/just-skyline-474622-e1/secrets/PINECONE_API_KEY/versions/latest
      env: 'PINECONE_API_KEY'
    - versionName: projects/just-skyline-474622-e1/secrets/PINECONE_API_ENVIRONMENT/versions/latest
      env: 'PINECONE_API_ENVIRONMENT'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8
  diskSizeGb: 50
