# cloudbuild_app.yaml
steps:
# 1. Build and tag
- name: gcr.io/cloud-builders/docker
  args:
    - build
    - -t
    - us-east1-docker.pkg.dev/just-skyline-474622-e1/rag/rag:$SHORT_SHA
    - -t
    - us-east1-docker.pkg.dev/just-skyline-474622-e1/rag/rag:latest
    - -f
    - ./Dockerfile_app
    - .

# 2. Push both tags
- name: gcr.io/cloud-builders/docker
  args:
    - push
    - us-east1-docker.pkg.dev/just-skyline-474622-e1/rag/rag:$SHORT_SHA
- name: gcr.io/cloud-builders/docker
  args:
    - push
    - us-east1-docker.pkg.dev/just-skyline-474622-e1/rag/rag:latest

# 3. Deploy to Cloud Run
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  id: deploy
  entrypoint: gcloud
  args:
    - run
    - deploy
    - rag-service
    - --image
    - us-east1-docker.pkg.dev/just-skyline-474622-e1/rag/rag:$SHORT_SHA
    - --region
    - us-east1
    - --allow-unauthenticated
    - --service-account
    - cloud-run-backend@just-skyline-474622-e1.iam.gserviceaccount.com
    - --min-instances
    - "1"
    - --max-instances
    - "10"
    - --memory
    - 4Gi
    - --cpu
    - "2"
    - --set-env-vars
    - UVICORN_WORKERS=1,SECRET_PROJECT_ID=just-skyline-474622-e1
    - --update-secrets
    - OPENAI_API_KEY=OPENAI_API_KEY:latest,PINECONE_API_KEY=PINECONE_API_KEY:latest,PINECONE_API_ENVIRONMENT=PINECONE_API_ENVIRONMENT:latest,EMBEDDING_MODEL_NAME_OSS=EMBEDDING_MODEL_NAME_OSS:latest,EMBEDDING_MODEL_NAME_OPENAI=EMBEDDING_MODEL_NAME_OPENAI:latest,EMBEDDING_MODEL_NAME=EMBEDDING_MODEL_NAME:latest,ENVIRONMENT=ENVIRONMENT:latest,NUM_CHUNKS_RETRIEVED=NUM_CHUNKS_RETRIEVED:latest,MIN_CHUNKS_FOR_RESPONSE=MIN_CHUNKS_FOR_RESPONSE:latest,NUM_CHUNKS_SEARCHED_FOR_RERANKING=NUM_CHUNKS_SEARCHED_FOR_RERANKING:latest,LLM_MODEL_NAME=LLM_MODEL_NAME:latest,LLM_MODEL_NAME_OSS=LLM_MODEL_NAME_OSS:latest,LLM_MODEL_NAME_OPENAI=LLM_MODEL_NAME_OPENAI:latest,PINECONE_INDEX_NAME=PINECONE_INDEX_NAME:latest,EMBED_PROVIDER=EMBED_PROVIDER:latest,EMBED_MODEL=EMBED_MODEL:latest,EMBED_DIM=EMBED_DIM:latest,PINECONE_NAMESPACE=PINECONE_NAMESPACE:latest,YT_NAMESPACE_CONFIG=YT_NAMESPACE_CONFIG:latest,PINECONE_NAMESPACE_VIDEOS=PINECONE_NAMESPACE_VIDEOS:latest,PINECONE_NAMESPACE_STREAMS=PINECONE_NAMESPACE_STREAMS:latest,PIPELINE_STORAGE_DIR=PIPELINE_STORAGE_DIR:latest,VOICE_LIBRARY_DIR=VOICE_LIBRARY_DIR:latest,SPEAKER_EMBED_CACHE_DIR=SPEAKER_EMBED_CACHE_DIR:latest,VOICE_MATCH_THRESHOLD=VOICE_MATCH_THRESHOLD:latest,SPEAKER_MAP_DIR=SPEAKER_MAP_DIR:latest,VOICE_EMBED_BACKEND=VOICE_EMBED_BACKEND:latest,VOICE_AUTO_ENROLL=VOICE_AUTO_ENROLL:latest,VOICE_ENROLL_MIN_TALK_S=VOICE_ENROLL_MIN_TALK_S:latest,VOICE_AUTO_ENROLL_NAME=VOICE_AUTO_ENROLL_NAME:latest



# List an image so Cloud Build shows a link
images:
- us-east1-docker.pkg.dev/just-skyline-474622-e1/rag/rag:$SHORT_SHA

options:
  logging: CLOUD_LOGGING_ONLY
