# cloudbuild_app.yaml
steps:
# 1. Build and tag
- name: gcr.io/cloud-builders/docker
  args:
    - build
    - -t
    - us-east1-docker.pkg.dev/just-skyline-474622-e1/rag/rag:$SHORT_SHA
    - -t
    - us-east1-docker.pkg.dev/just-skyline-474622-e1/rag/rag:latest
    - -f
    - ./Dockerfile_app
    - .

# 2. Push both tags
- name: gcr.io/cloud-builders/docker
  args:
    - push
    - us-east1-docker.pkg.dev/just-skyline-474622-e1/rag/rag:$SHORT_SHA
- name: gcr.io/cloud-builders/docker
  args:
    - push
    - us-east1-docker.pkg.dev/just-skyline-474622-e1/rag/rag:latest

# 3. Deploy to Cloud Run
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  id: deploy
  entrypoint: gcloud
  args:
    - run
    - deploy
    - rag-service
    - --image
    - us-east1-docker.pkg.dev/just-skyline-474622-e1/rag/rag:$SHORT_SHA
    - --region
    - us-east1
    - --allow-unauthenticated
    - --service-account
    - cloud-run-backend@just-skyline-474622-e1.iam.gserviceaccount.com
    - --min-instances
    - "1"
    - --max-instances
    - "10"
    - --memory
    - 4Gi
    - --cpu
    - "2"
    - --set-env-vars
    - UVICORN_WORKERS=1,SECRET_PROJECT_ID=just-skyline-474622-e1
    - --update-secrets
    - OPENAI_API_KEY=OPENAI_API_KEY:latest,PINECONE_API_KEY=PINECONE_API_KEY:latest,PINECONE_API_ENVIRONMENT=PINECONE_API_ENVIRONMENT:latest



# List an image so Cloud Build shows a link
images:
- us-east1-docker.pkg.dev/just-skyline-474622-e1/rag/rag:$SHORT_SHA

options:
  logging: CLOUD_LOGGING_ONLY
